name: Node CI B&B

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    name: testAndBuild
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/bulls-n-bears/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn build
      - run: yarn test --watchAll=false
      - run: yarn deploy
